### ISSUE TITLE
How do I activate the "AMQP sender routine"

### ISSUE THREAD

**Issue by laroque** [project8/hornet#23]
There is not configuration section for a "sender" that I can find, but trying to start hornet using the example config produces:

```
[Classifier] ▶ Cannot start classifier because the AMQP sender routine is not active, and sending file info has been requested
```

I'm marking this as a "question" not a "bug" because I know it has worked, so I believe that the feature is probably fine, and I just am not understanding the required configuration.

**Comment by nsoblath** [comment]
The AMQP sender and receiver are both started by setting "amqp.active" to true.

Getting that error message is either a result of the sender failing to start (in which case you should be able to find an associated error message), or there being some delay in it starting.  The latter can happen because of network traffic or who knows what else, so I added a configurable wait time in the classifier configuration: "wait-for-sender".  The classifier checks the sender, and it it's not already running, waits that number of seconds to check it again; at that point, if it's still not running, you get that error message.

**Comment by nsoblath** [comment]
Assuming this is working now.
