### ISSUE TITLE
Full disk causes RSA to crash

### ISSUE THREAD

**Issue by ldeviveiros** [project8/hornet#31]
When /data/warm fills up, Hornet causes the RSA software to crash.

**Comment by nsoblath** [comment]
Is this new behavior?  I don't recall it happening in the disk-fills that happened last weekend, but maybe I just didn't hear about them.

I don't quite understand why the RSA is affected.  Previously we've seen the RSA crash when access to a file it's trying to write is locked.  But I don't think that would have been occurring in this case.  Obviously the crash doesn't happen immediately, since many files fail to copy.  Do you know if there's something specific that triggers the crash?

**Comment by nsoblath** [comment]
I don't think this is a hornet issue; if I'm wrong and something needs to be fixed, it should be reopened.
